### PR TITLE
Fix: client/server item ownership communication

### LINKED ISSUE #257: Client / Server Not Communicating Item Ownership and Mob Community
### Summary:

We previously implemented community-based ownership (particularly applied to potion stands). While our implementation works in terms of server authentication, we realized in doing this that the client and server are not communicating item ownership and mob community. This results in inconsistencies between client-side behavior and the authoritative server state.

### Goal:

Ensure that the client and server correctly synchronize ownership information for items and mob community, preventing desync issues and maintaining consistent game logic.

### Deliverables:
- TBD

### Bug Discovery:

During ownership implementation, we observed that while server authentication works for community-based ownership, the client does not always correctly display item ownership and mob community.

### PR DESCRIPTION
**Pull request by nonetypes**
## Fix #257: client/server item ownership communication

**Group:** Bernette Chan, Chelsey Harper, Harshini Karthikeyan, Alex Ralston

## Summary
We previously implemented community-based ownership and applied it to potion stands, successfully enforcing server-side authentication. However, we discovered that the client and server are not properly communicating item ownership. As a result, the client did not reflect the correct ownership status, which prevented it from properly displaying, or not displaying, permissible/restricted interactions in the UI.

This PR ensures that item ownership is correctly transmitted from the server to the client, allowing for accurate display and interaction restrictions where applicable.

## Changes
- `packages/client/src/sprite/sprite_item.ts`: Add ownedBy fields to SpriteItem.
- `packages/common/src/item.ts`: Add ownedBy field to ItemI.
- `packages/client/src/world/controller.ts`: Comment out debugging messages.
- `packages/server/src/services/clientCommunication/clientMarshalling.ts`: Pass ownedBy to ItemI in itemDatatoItem. Add owned_by to to getItemAbly query.
- `packages/server/src/items/uses/create.ts`: Pass in mob community to itemGenerator.createItem.
- `packages/client/test/items/uses/playerPermissibleInteractions.test.ts`: Add unit test.

### CODE REVIEW

File: packages/client/src/world/controller.ts [hunk 1]
```diff
@@ -195,6 +195,7 @@ export function getPhysicalInteractions(
   const interactions: Interactions[] = [];
   const item = physical as Item;
   const isOwner = item.isOwnedBy(currentCharacter?.community_id);
+  // console.log("Mob community:", currentCharacter?.community_id, "item ownedby:", item.ownedBy, "Is Owner:", isOwner);
```
Comment (StarDylan) [inline packages/client/src/world/controller.ts:198]: We should delete these instead of commenting it out. Since it adds noise to the codebase

File: packages/client/src/world/controller.ts [hunk 2]
```diff
@@ -403,6 +404,7 @@ export function setDate(date: FantasyDateI) {
 }
 
 export function addNewItem(scene: WorldScene, item: ItemI) {
+  // console.log("Adding new item from client side:", item);
```
Comment (StarDylan) [inline packages/client/src/world/controller.ts:407]: Same here

**Review by StarDylan — CHANGES_REQUESTED** [review]
Some style changes, otherwise looks good

**Review by StarDylan — APPROVED** [review]
